import numpy as np
import pandas as pd
from typing import Dict, Any, List, Tuple, Optional
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier, GradientBoostingRegressor
from sklearn.linear_model import LogisticRegression

from app.ai.synthetic import generate_synthetic_dataset
from app.ai.features import engineer_features
from app.ai.ml_dataset import (
    build_employment_dataset,
    build_salary_dataset,
    build_retention_dataset
)
from app.ai.ml_preprocessing import build_preprocessing_pipeline

# Safe observable feature contracts
SAFE_PRE_EMPLOYMENT_FEATURES = [
    "programme_id",
    "district",
    "avg_skill_score",
    "total_assessments"
]

SAFE_PLACEMENT_FEATURES = [
    "latest_salary"
]

FORBIDDEN_LEAKAGE_FEATURES = [
    "retained_3m",
    "retained_6m",
    "retained_12m",
    "employment_duration_days",
    "max_duration_days",
    "wage_growth_amount",
    "wage_growth_percentage",
    "employer_feedback",
    "satisfaction_score",
    "technical_deficiencies",
    "latent_ability",
    "quality_factor",
    "target_job_id"
]

SYNTHETIC_DISCLAIMER = (
    "These predictions are generated by models trained exclusively on synthetic experimental data. "
    "They serve as an advisory decision-support tool and must not be interpreted as guaranteed or real-world human outcomes."
)

SALARY_UNCERTAINTY_WARNING = (
    "Salary prediction has substantial residual uncertainty (Phase 7D Holdout R² ≈ -0.088, RMSE ≈ $3,894) "
    "and should be treated as a rough baseline estimate rather than guaranteed compensation."
)

_CACHED_MODELS: Optional[Dict[str, Any]] = None


def load_inference_models(force_reload: bool = False) -> Dict[str, Any]:
    """
    Initializes and caches the three finalized Phase 7 ML pipelines.
    Trains each pipeline on the isolated 80% development partitions using seed=42.
    """
    global _CACHED_MODELS
    if _CACHED_MODELS is not None and not force_reload:
        return _CACHED_MODELS
        
    raw_dfs = generate_synthetic_dataset(num_trainees=5000, seed=42)
    engineered = engineer_features(raw_dfs)
    
    # 1. Employment Model Pipeline (Phase 7C Best Model: RandomForestClassifier)
    X_emp, y_emp, meta_emp = build_employment_dataset(engineered, raw_dfs)
    X_train_emp, _, y_train_emp, _ = train_test_split(
        X_emp, y_emp, test_size=0.2, random_state=42, stratify=y_emp
    )
    preprocessor_emp = build_preprocessing_pipeline(
        meta_emp["categorical_features"], meta_emp["numerical_features"]
    )
    emp_pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor_emp),
        ("classifier", RandomForestClassifier(
            n_estimators=100, max_depth=5, min_samples_split=2,
            min_samples_leaf=1, max_features="sqrt", random_state=42
        ))
    ])
    emp_pipeline.fit(X_train_emp, y_train_emp)
    
    # 2. Salary Model Pipeline (Phase 7D Best Model: GradientBoostingRegressor)
    X_sal, y_sal, meta_sal = build_salary_dataset(engineered, raw_dfs)
    X_train_sal, _, y_train_sal, _ = train_test_split(
        X_sal, y_sal, test_size=0.2, random_state=42
    )
    preprocessor_sal = build_preprocessing_pipeline(
        meta_sal["categorical_features"], meta_sal["numerical_features"]
    )
    sal_pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor_sal),
        ("regressor", GradientBoostingRegressor(
            learning_rate=0.01, max_depth=3, min_samples_split=10,
            n_estimators=50, random_state=42
        ))
    ])
    sal_pipeline.fit(X_train_sal, y_train_sal)
    
    # 3. Retention Model Pipeline (Phase 7E Best Model: LogisticRegression)
    X_ret, y_ret, meta_ret = build_retention_dataset(engineered, raw_dfs)
    X_train_ret, _, y_train_ret, _ = train_test_split(
        X_ret, y_ret, test_size=0.2, random_state=42, stratify=y_ret
    )
    preprocessor_ret = build_preprocessing_pipeline(
        meta_ret["categorical_features"], meta_ret["numerical_features"]
    )
    ret_pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor_ret),
        ("classifier", LogisticRegression(C=10.0, max_iter=1000, random_state=42))
    ])
    ret_pipeline.fit(X_train_ret, y_train_ret)
    
    _CACHED_MODELS = {
        "employment_pipeline": emp_pipeline,
        "salary_pipeline": sal_pipeline,
        "retention_pipeline": ret_pipeline,
        "metadata": {
            "version": "Phase_7F_Unified_v1.0",
            "provenance": {
                "employment_model": "RandomForestClassifier_Phase_7C (CV ROC-AUC: 0.916)",
                "salary_model": "GradientBoostingRegressor_Phase_7D (Holdout RMSE: $3,894)",
                "retention_model": "LogisticRegression_Phase_7E (Holdout ROC-AUC: 0.911)"
            },
            "synthetic_data": True
        }
    }
    return _CACHED_MODELS


def validate_prediction_input(
    input_data: Dict[str, Any],
    require_salary: bool = False
) -> Tuple[bool, List[str]]:
    """
    Validates input schema, verifies ranges, and strictly rejects forbidden leakage fields.
    """
    errors = []
    
    if not isinstance(input_data, dict):
        return False, ["Input data must be a dictionary"]
        
    # Check for forbidden leakage fields
    forbidden_present = [k for k in input_data.keys() if k in FORBIDDEN_LEAKAGE_FEATURES]
    if forbidden_present:
        errors.append(
            f"Forbidden leakage/downstream features detected: {forbidden_present}. "
            f"These fields violate temporal prediction boundaries and must not be supplied."
        )
        
    # Check required pre-employment fields
    for field in SAFE_PRE_EMPLOYMENT_FEATURES:
        if field not in input_data or input_data[field] is None:
            errors.append(f"Missing required pre-employment field: '{field}'")
            
    # Validate numerical boundaries if present
    if "avg_skill_score" in input_data and input_data["avg_skill_score"] is not None:
        try:
            score = float(input_data["avg_skill_score"])
            if not (0.0 <= score <= 100.0):
                errors.append(f"'avg_skill_score' must be between 0.0 and 100.0, got {score}")
        except (ValueError, TypeError):
            errors.append(f"'avg_skill_score' must be numeric, got {input_data['avg_skill_score']}")
            
    if "total_assessments" in input_data and input_data["total_assessments"] is not None:
        try:
            assessments = int(input_data["total_assessments"])
            if assessments < 0:
                errors.append(f"'total_assessments' must be non-negative, got {assessments}")
        except (ValueError, TypeError):
            errors.append(f"'total_assessments' must be integer, got {input_data['total_assessments']}")
            
    # Check salary validation if provided or required
    if require_salary:
        if "latest_salary" not in input_data or input_data["latest_salary"] is None:
            errors.append("Field 'latest_salary' is required for post-placement retention prediction.")
            
    if "latest_salary" in input_data and input_data["latest_salary"] is not None:
        try:
            salary = float(input_data["latest_salary"])
            if salary < 0.0:
                errors.append(f"'latest_salary' must be non-negative, got {salary}")
        except (ValueError, TypeError):
            errors.append(f"'latest_salary' must be numeric, got {input_data['latest_salary']}")
            
    return len(errors) == 0, errors


def _get_decision_band(probability: float) -> str:
    """Assigns decision-support uncertainty band to predicted probability."""
    if probability < 0.40:
        return "LOW_PROBABILITY"
    elif probability <= 0.60:
        return "HIGH_UNCERTAINTY_REVIEW_RECOMMENDED"
    else:
        return "HIGH_PROBABILITY"


def predict_employment(
    input_data: Dict[str, Any],
    models: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Executes pre-employment classification inference: P(is_employed).
    """
    is_valid, errors = validate_prediction_input(input_data, require_salary=False)
    if not is_valid:
        raise ValueError(f"Input validation failed: {'; '.join(errors)}")
        
    models = models or load_inference_models()
    pipeline = models["employment_pipeline"]
    
    df = pd.DataFrame([{
        "programme_id": str(input_data["programme_id"]),
        "district": str(input_data["district"]),
        "avg_skill_score": float(input_data["avg_skill_score"]),
        "total_assessments": int(input_data["total_assessments"])
    }])
    
    prob = float(pipeline.predict_proba(df)[0, 1])
    pred = int(pipeline.predict(df)[0])
    band = _get_decision_band(prob)
    
    explanations = generate_explanation("employment", input_data, models)
    
    return {
        "probability": round(prob, 4),
        "prediction": pred,
        "confidence_band": band,
        "prediction_point": "pre_employment",
        "explanations": explanations,
        "provenance": models["metadata"]["provenance"]["employment_model"],
        "disclaimer": SYNTHETIC_DISCLAIMER
    }


def predict_salary(
    input_data: Dict[str, Any],
    models: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Executes salary regression inference conditional on placement.
    """
    is_valid, errors = validate_prediction_input(input_data, require_salary=False)
    if not is_valid:
        raise ValueError(f"Input validation failed: {'; '.join(errors)}")
        
    models = models or load_inference_models()
    pipeline = models["salary_pipeline"]
    
    df = pd.DataFrame([{
        "programme_id": str(input_data["programme_id"]),
        "district": str(input_data["district"]),
        "avg_skill_score": float(input_data["avg_skill_score"]),
        "total_assessments": int(input_data["total_assessments"])
    }])
    
    predicted_salary = float(pipeline.predict(df)[0])
    predicted_salary = max(0.0, predicted_salary)
    
    explanations = generate_explanation("salary", input_data, models)
    
    return {
        "predicted_salary": round(predicted_salary, 2),
        "prediction_context": "conditional_on_placement",
        "prediction_point": "placement_intake",
        "warning": SALARY_UNCERTAINTY_WARNING,
        "explanations": explanations,
        "provenance": models["metadata"]["provenance"]["salary_model"],
        "disclaimer": SYNTHETIC_DISCLAIMER
    }


def predict_retention(
    input_data: Dict[str, Any],
    models: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Executes retention classification inference conditional on placement and salary availability.
    """
    is_valid, errors = validate_prediction_input(input_data, require_salary=True)
    if not is_valid:
        raise ValueError(f"Input validation failed: {'; '.join(errors)}")
        
    models = models or load_inference_models()
    pipeline = models["retention_pipeline"]
    
    df = pd.DataFrame([{
        "programme_id": str(input_data["programme_id"]),
        "district": str(input_data["district"]),
        "avg_skill_score": float(input_data["avg_skill_score"]),
        "total_assessments": int(input_data["total_assessments"]),
        "latest_salary": float(input_data["latest_salary"])
    }])
    
    prob = float(pipeline.predict_proba(df)[0, 1])
    pred = int(pipeline.predict(df)[0])
    band = _get_decision_band(prob)
    
    explanations = generate_explanation("retention", input_data, models)
    
    return {
        "probability": round(prob, 4),
        "prediction": pred,
        "confidence_band": band,
        "prediction_context": "conditional_on_placement_and_salary",
        "prediction_point": "post_placement_pre_retention",
        "explanations": explanations,
        "provenance": models["metadata"]["provenance"]["retention_model"],
        "disclaimer": SYNTHETIC_DISCLAIMER
    }


def generate_explanation(
    model_type: str,
    input_data: Dict[str, Any],
    models: Optional[Dict[str, Any]] = None
) -> List[str]:
    """
    Generates non-causal, model-derived explanatory associations based on feature importance.
    """
    explanations = []
    prog = input_data.get("programme_id", "Unknown")
    district = input_data.get("district", "Unknown")
    score = input_data.get("avg_skill_score", 0.0)
    
    if model_type == "employment":
        if score >= 70.0:
            explanations.append(f"Candidate average skill score ({score}) is positively associated with employment likelihood in this model.")
        else:
            explanations.append(f"Candidate average skill score ({score}) indicates potential skill gaps that are associated with lower placement rates.")
        explanations.append(f"Training programme '{prog}' provides curriculum alignment context for employment prediction.")
        
    elif model_type == "salary":
        explanations.append(f"Skill score ({score}) and programme '{prog}' are the primary observable signals used in baseline salary estimation.")
        explanations.append("Salary estimates carry high residual variance as specific hiring firm and job role requirements remain unobserved.")
        
    elif model_type == "retention":
        salary = input_data.get("latest_salary")
        if salary is not None:
            if float(salary) >= 35000:
                explanations.append(f"Starting compensation level (${salary:,.2f}) is positively associated with 6-month retention likelihood in this model.")
            else:
                explanations.append(f"Starting compensation level (${salary:,.2f}) is associated with moderate retention in this model.")
        explanations.append(f"Programme '{prog}' in district '{district}' provides geographical and domain context for retention.")
        
    # Append mandatory non-causal statement
    explanations.append("Note: These statements reflect model-derived statistical associations and do NOT imply direct causal effects.")
    return explanations


def generate_trajectory_prediction(
    input_data: Dict[str, Any],
    models: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Generates a unified decision-support trajectory connecting:
    P(employment) -> Expected Salary -> P(6-month retention).
    Explicitly handles Pre-Employment State (State A) and Post-Placement State (State B).
    """
    is_valid, errors = validate_prediction_input(input_data, require_salary=False)
    if not is_valid:
        raise ValueError(f"Input validation failed: {'; '.join(errors)}")
        
    models = models or load_inference_models()
    
    # 1. Step 1: Pre-Employment Prediction
    emp_res = predict_employment(input_data, models)
    
    # 2. Step 2: Salary Prediction (Conditional on Placement)
    sal_res = predict_salary(input_data, models)
    
    # 3. Step 3: Retention Prediction (Conditional on Placement & Known Salary)
    has_known_salary = "latest_salary" in input_data and input_data["latest_salary"] is not None
    
    if has_known_salary:
        ret_res = predict_retention(input_data, models)
        prediction_point = "post_placement"
        salary_block = {
            "available": True,
            "known_salary": float(input_data["latest_salary"]),
            "predicted_baseline_salary": sal_res["predicted_salary"],
            "prediction_context": "observed_at_placement",
            "warning": None
        }
        retention_block = {
            "available": True,
            "probability": ret_res["probability"],
            "prediction": ret_res["prediction"],
            "confidence_band": ret_res["confidence_band"],
            "prediction_context": "conditional_on_placement_and_salary"
        }
    else:
        prediction_point = "pre_employment"
        salary_block = {
            "available": True,
            "known_salary": None,
            "predicted_salary": sal_res["predicted_salary"],
            "prediction_context": "conditional_on_placement",
            "warning": sal_res["warning"]
        }
        retention_block = {
            "available": False,
            "probability": None,
            "prediction": None,
            "confidence_band": "UNAVAILABLE_PRE_PLACEMENT",
            "prediction_context": "conditional_on_placement",
            "reason": "Retention prediction requires confirmed placement salary and employment context."
        }
        
    # 4. Trajectory Stage & Qualitative Category
    # Rules for qualitative decision category:
    emp_prob = emp_res["probability"]
    ret_prob = retention_block["probability"]
    
    if emp_res["confidence_band"] == "HIGH_UNCERTAINTY_REVIEW_RECOMMENDED" or (
        retention_block["available"] and retention_block["confidence_band"] == "HIGH_UNCERTAINTY_REVIEW_RECOMMENDED"
    ):
        qualitative_category = "HUMAN REVIEW"
        trajectory_summary = "Prediction probabilities fall in the uncertainty boundary (0.40 - 0.60). Human counselor review is advised."
    elif emp_prob >= 0.60 and (ret_prob is None or ret_prob >= 0.60):
        qualitative_category = "HIGH POTENTIAL"
        trajectory_summary = "High probability of placement and strong projected retention stability."
    elif emp_prob < 0.40 or (ret_prob is not None and ret_prob < 0.40):
        qualitative_category = "LOW POTENTIAL"
        trajectory_summary = "Lower projected probability of placement or retention. Targeted skilling intervention recommended."
    else:
        qualitative_category = "MODERATE POTENTIAL"
        trajectory_summary = "Moderate placement likelihood with typical retention indicators."
        
    warnings = [SYNTHETIC_DISCLAIMER]
    if not has_known_salary:
        warnings.append(SALARY_UNCERTAINTY_WARNING)
        warnings.append("Retention probability is marked unavailable because placement salary has not been established.")
        
    unified_explanations = emp_res["explanations"] + (ret_res["explanations"] if has_known_salary else sal_res["explanations"])
    # Deduplicate non-causal disclaimer notes
    clean_explanations = [e for e in unified_explanations if not e.startswith("Note:")]
    clean_explanations.append("Note: All explanations reflect model-derived statistical associations and do NOT imply direct causal effects.")
    
    return {
        "prediction_version": models["metadata"]["version"],
        "prediction_point": prediction_point,
        "employment": {
            "probability": emp_res["probability"],
            "prediction": emp_res["prediction"],
            "confidence_band": emp_res["confidence_band"]
        },
        "salary": salary_block,
        "retention": retention_block,
        "trajectory": {
            "stage": "Placed & Active" if has_known_salary else "In Training / Pre-Placement",
            "qualitative_category": qualitative_category,
            "summary": trajectory_summary
        },
        "explanations": clean_explanations,
        "warnings": warnings,
        "provenance": models["metadata"]["provenance"]
    }
