import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, BarChart3, Building2, Check, CheckCircle2, ChevronDown, ShieldCheck, Sparkles, Target, TrendingUp, UserRound, Users } from "lucide-react";
import "./LandingPage.css";

const portals = [
  ["trainee", "Trainee", UserRound, "/landing-trainee.png", ["Update outcomes", "Track employment journey", "Report wages & retention", "Give feedback"]],
  ["employer", "Employer", Building2, "/landing-employer.png", ["Verify employment", "Confirm workforce", "Report skill gaps", "Provide feedback"]],
  ["admin", "Government", BarChart3, "/landing-admin.png", ["Monitor outcomes", "Compare providers", "Identify skill gaps", "Simulate interventions"]],
];
const steps = [["01", "Check in", "Trainees update employment and outcome status."], ["02", "Verify", "Employer and verified sources validate employment information."], ["03", "Track", "3 / 6 / 12-month follow-ups capture retention, wages and relevance."], ["04", "Analyze", "Identify skill gaps, outcome trends and provider performance."], ["05", "Act", "Simulate interventions and support corrective action."]];

export default function LandingPage() {
  const navigate = useNavigate(); const [modal, setModal] = useState(false); const [role, setRole] = useState("admin");
  const scroll = (id) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  const login = (selected = "admin") => { setRole(selected); setModal(true); };
  const enter = () => { localStorage.setItem("userRole", role); localStorage.setItem("sih_token", `demo_${role}_jwt_token_verified`); if (role === "trainee") localStorage.setItem("traineeId", "TR-0001"); if (role === "employer") { localStorage.setItem("organizationId", "EMP-DEMO-001"); localStorage.setItem("organizationName", "Tata Consultancy Services"); } navigate(role === "admin" ? "/admin" : `/${role}`); };
  return <div className="s2i-page">
    <header className="s2i-nav"><button className="s2i-brand" onClick={() => scroll("home")}><img src="/skill2impact-logo.png" alt="Skill2Impact" /><span>From Skills to Measurable Employment Impact</span></button><nav><button onClick={() => scroll("home")}>Home</button><button onClick={() => scroll("how")}>How It Works</button><button onClick={() => scroll("dashboards")}>Dashboards</button><button onClick={() => scroll("impact")}>Impact</button><button className="s2i-login" onClick={() => login()}>Login <ArrowRight size={16} /></button></nav></header>
    <main id="home">
      <section className="s2i-hero s2i-container"><div><p className="s2i-kicker">Skilling Outcome Intelligence Platform</p><h1>Beyond certification.<br /><span>Track what happens next.</span></h1><p className="s2i-lede">Connect training data with employment, retention, wage progression and skill relevance — and turn outcome intelligence into actionable policy decisions.</p><div className="s2i-actions"><button className="s2i-primary" onClick={() => scroll("dashboards")}>Explore Platform <ArrowRight size={17} /></button><button className="s2i-secondary" onClick={() => login()}>Login</button></div><div className="s2i-journey">Train <ArrowRight /> Certify <ArrowRight /> Employ <ArrowRight /> Retain <ArrowRight /> Improve</div></div><Screen image="/landing-admin.png" label="Skill2Impact · Executive Outcome Dashboard" alt="Actual Skill2Impact government dashboard" hero /></section>
      <section className="s2i-section s2i-container"><Heading label="The outcome gap" title={<>Training is tracked. <span>Impact isn't.</span></>} /><div className="s2i-gap-grid"><Gap title="What is already tracked" items={["Enrolment", "Attendance", "Assessment", "Certification"]} /><Gap title="What remains unclear" items={["Employment & Retention", "Non-placement / Attrition", "Wage Progression", "Skill Relevance"]} unclear /></div><p className="s2i-bridge">Skill2Impact connects these missing outcomes into a longitudinal view of skilling impact.</p></section>
      <section className="s2i-section s2i-soft" id="how"><div className="s2i-container"><Heading center label="How it works" title={<>From Training Data to <span>Measurable Impact</span></>} /><div className="s2i-steps">{steps.map(([n,t,d],i) => <article className="s2i-step" key={t}><b>{n}</b><i>{i < 4 ? <ChevronDown /> : <Target />}</i><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
      <section className="s2i-section s2i-container" id="dashboards"><Heading label="Connected dashboards" title={<>One Platform. <span>Three Perspectives.</span></>} text="Each portal serves the people who create, verify and act on outcome intelligence." /><div className="s2i-dashboard-grid">{portals.map(([key,title,Icon,img,items]) => <article className="s2i-dashboard" key={key}><div className="s2i-card-title"><Icon /><div><h3>{title}</h3><p>{title === "Government" ? "Outcome intelligence" : `${title} portal`}</p></div></div><img src={img} alt={`Actual Skill2Impact ${title} dashboard`} /><ul>{items.map(x => <li key={x}><Check />{x}</li>)}</ul><button onClick={() => login(key)}>Open {title} portal <ArrowRight /></button></article>)}</div></section>
      <section className="s2i-section s2i-container"><Heading label="Purpose-built intelligence" title={<>Why <span>Skill2Impact?</span></>} /><div className="s2i-value-grid">{[[ShieldCheck,"Confidence-Aware","Multi-tier verification"],[Users,"Triangulated","Employer + Trainee + Verified Syllabus"],[Sparkles,"Simulation-Driven","Simulate policy impact before action"],[TrendingUp,"Action-Driven","Insights → Action → Impact"]].map(([Icon,title,text],i) => <article key={title}><b>0{i+1}</b><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="s2i-section s2i-soft"><div className="s2i-container"><Heading center label="Outcome intelligence" title={<>From Data to <span>Decisions</span></>} /><div className="s2i-decision"><div className="s2i-outcomes">{["Employment","Retention","Wage Growth","Skill Relevance","Non-placement / Attrition"].map(x => <span key={x}>{x}</span>)}</div><div className="s2i-flow"><b>Outcome Data</b><ArrowRight /><b>Intelligence</b><ArrowRight /><b>Intervention</b><ArrowRight /><b>Measured Impact</b></div></div></div></section>
      <section className="s2i-section s2i-container"><div className="s2i-simulation"><div><p className="s2i-kicker">Simulation / Projection</p><h2>Test Interventions Before Rollout</h2><p>Simulate potential policy or training interventions using outcome data before implementation.</p><button className="s2i-primary" onClick={() => login("admin")}>Explore policy simulation <ArrowRight /></button></div><div><Screen image="/landing-simulation.png" label="Policy Simulation" alt="Actual Skill2Impact policy simulation interface" /><p className="s2i-projection">Policy Scenario: Retraining Intervention <ArrowRight /> Simulated Impact <ArrowRight /> Placement / Outcome Change</p></div></div></section>
      <section className="s2i-section s2i-container" id="impact"><Heading center label="Impact framework" title={<>Measuring What Happens <span>After Training</span></>} /><div className="s2i-impact-grid">{[["3 / 6 / 12 Months","Longitudinal follow-up"],["3 User Roles","Trainee • Employer • Government"],["5 Outcome Areas","Employment • Retention • Wages • Skills • Attrition"],["Multi-tier","Outcome verification"]].map(([a,b]) => <article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section>
      <section className="s2i-final"><div className="s2i-container"><div><p className="s2i-kicker">Skill2Impact</p><h2>Beyond certification. Measure real impact.</h2><p>Skill2Impact connects training data with the employment outcomes that matter.</p></div><div className="s2i-actions"><button className="s2i-light" onClick={() => scroll("dashboards")}>Explore Platform</button><button className="s2i-outline" onClick={() => login()}>Login</button></div></div></section>
    </main>
    <footer className="s2i-footer"><div className="s2i-container"><div><strong>Skill2Impact</strong><p>From Skills to Measurable Employment Impact</p></div><p>Trainee &nbsp;|&nbsp; Employer &nbsp;|&nbsp; Government</p></div></footer>
    {modal && <div className="s2i-modal-backdrop" onClick={() => setModal(false)}><div className="s2i-modal" onClick={e => e.stopPropagation()}><button className="s2i-close" onClick={() => setModal(false)}>×</button><p className="s2i-kicker">Secure platform access</p><h2>Choose your portal</h2><p>Open the Skill2Impact prototype as the relevant platform user.</p><div className="s2i-tabs">{portals.map(([key,title,Icon]) => <button key={key} className={role === key ? "active" : ""} onClick={() => setRole(key)}><Icon />{title}</button>)}</div><div className="s2i-modal-card"><span>{role === "admin" ? "Government / Admin" : role}</span><h3>Open the {role === "admin" ? "government" : role} dashboard</h3><p>Demo access opens the existing interactive prototype with its working data and workflows.</p><button className="s2i-primary" onClick={enter}>Continue to portal <ArrowRight /></button></div></div></div>}
  </div>;
}
function Heading({label,title,text,center}) { return <div className={`s2i-heading ${center ? "center" : ""}`}><p className="s2i-kicker">{label}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Gap({title,items,unclear}) { return <article className={`s2i-gap ${unclear ? "unclear" : ""}`}><h3>{title}</h3>{items.map(x => <p key={x}>{unclear ? <i>?</i> : <CheckCircle2 />}{x}</p>)}</article>; }
function Screen({image,label,alt,hero}) { return <div className={`s2i-screen ${hero ? "hero" : ""}`}><div className="s2i-window"><i /><i /><i /><span>{label}</span></div><img src={image} alt={alt} /></div>; }
